MODEL = "claude-sonnet-5"
CONCURRENCY_LIMIT = 3  # asyncio.Semaphore cap across parallel burst page invocations
SUPPORTED_DOC_TYPES = {"invoice", "scientific_paper", "contract"}
FALLBACK_DOC_TYPE = "baseline_core"
COLUMN_BUCKET_PX = 50  # xmin bucket width for geometric pre-sorter column grouping
EXTRACTION_NOTE_MAX_LENGTH = 200  # max chars for extraction_note; injected into all schemas at load time
VALIDATION_MAX_RETRIES = 3  # max schema-validation retries for both pioneer (graph-level) and burst (inline)
HTTP_MAX_RETRIES = 3  # max tenacity retries on transient HTTP errors (429/529) at the API call site
EXTRACTION_TEMPERATURE = 0.0  # deterministic outputs for all extraction/classification/hierarchy API calls
CLASSIFIER_MAX_TOKENS = 10  # single-token classification response
WORKER_MAX_TOKENS = 4000  # token budget for page extraction worker
HIERARCHY_MAX_TOKENS_BASE = 4000  # minimum token budget for hierarchy agent
HIERARCHY_MAX_TOKENS_CEIL = 16000  # maximum token budget for hierarchy agent (scales with block count)
HIERARCHY_TOKENS_PER_BLOCK = 40  # token scaling factor: estimated tokens per block in hierarchy manifest
RETRY_BACKOFF_MULTIPLIER = 1  # tenacity exponential backoff multiplier (seconds)
RETRY_BACKOFF_MIN_SECONDS = 1  # minimum wait between HTTP retries (seconds)
RETRY_BACKOFF_MAX_SECONDS = 10  # maximum wait between HTTP retries (seconds)
